### ISSUE TITLE
What about Linux?

### ISSUE THREAD

**Issue by matt32106** [waynepiekarski/XPlaneMonitor#1]
I use the linux xplane 11 client. Any chance to make XPlaneMonitor work with Linux? (I noticed that extplane v2 provides only a win.xpl, no lin.xpl...)

**Comment by waynepiekarski** [comment]
The official ExtPlane page has releases for both Windows and Linux, so you should be able to download one of these and it will work for you: https://github.com/vranki/ExtPlane/releases

About a year ago, ExtPlane had some bugs which I needed workarounds for, and the releases were not working, so I built my own. But the latest releases should be good now, so give it a try.

**Comment by matt32106** [comment]
Wilco! Thanks.
